version: "3.3"
services:
  wecom:
    env_file:
      - dev.env
    image: 192.168.25.201:5000/xiuyuan/wecomchan:0.0.1-SNAPSHOT
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  backend: