version: "3.3"
services:
  wecom:
    env_file:
      - dev.env
    image: xiuyuan/wecomchan:gov1
    expose:
      - "8080"
    ports:
      - "8088:8080"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  backend: