server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: ${APPLICATION_NAME:wecomchan}

wecom:
  corpid: ${CORP_ID:CORP_ID}
  corpsecret: ${WECOM_SECRET:WECOM_SECRET}
  aid: ${WECOM_AID:WECOM_AID}
  token: ${WECOM_TOKEN:WECOM_TOKEN}
  encodingAesKey: ${WECOM_ENCODING_AES_KEY:WECOM_ENCODING_AES_KEY}
